-- Fase 5: ACL de reconstrucción, catálogo de producción consultado el 2026-09-21.
-- Solo para reproducir instalaciones locales/nuevas; no aplicar a producción.
-- Los defaults gestionados de supabase_admin permanecen fuera de este ajuste.
BEGIN;
REVOKE ALL ON FUNCTION public.activar_token(p_token text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.activar_token(p_token text) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.activar_token(p_token text) TO "service_role";
REVOKE ALL ON FUNCTION public.activar_token_docente(p_token text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.activar_token_docente(p_token text) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.activar_token_docente(p_token text) TO "service_role";
REVOKE ALL ON FUNCTION public.admin_cambiar_rol_usuario(p_usuario_id uuid, p_rol text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_cambiar_rol_usuario(p_usuario_id uuid, p_rol text) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.admin_cambiar_rol_usuario(p_usuario_id uuid, p_rol text) TO "service_role";
REVOKE ALL ON FUNCTION public.admin_crear_tokens_docente(p_escuela_id uuid, p_emails text[], p_expira_en timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_crear_tokens_docente(p_escuela_id uuid, p_emails text[], p_expira_en timestamp with time zone) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.admin_crear_tokens_docente(p_escuela_id uuid, p_emails text[], p_expira_en timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION public.admin_crear_tokens_libro(p_escuela_id uuid, p_libro_id text, p_grado_id integer, p_cantidad integer, p_expira_en timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_crear_tokens_libro(p_escuela_id uuid, p_libro_id text, p_grado_id integer, p_cantidad integer, p_expira_en timestamp with time zone) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.admin_crear_tokens_libro(p_escuela_id uuid, p_libro_id text, p_grado_id integer, p_cantidad integer, p_expira_en timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION public.admin_solicitar_accion_sensible(p_tipo text, p_payload jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_solicitar_accion_sensible(p_tipo text, p_payload jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.admin_solicitar_accion_sensible_v2(p_tipo text, p_payload jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_solicitar_accion_sensible_v2(p_tipo text, p_payload jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.admin_solicitar_accion_sensible_v2(p_tipo text, p_payload jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.auditar_actividad_admin() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.auditar_actividad_admin() TO "service_role";
REVOKE ALL ON FUNCTION public.bloquear_desactivacion_directa() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.bloquear_desactivacion_directa() TO "service_role";
REVOKE ALL ON FUNCTION public.buscar_clase_para_unirse(p_codigo text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.buscar_clase_para_unirse(p_codigo text) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.buscar_clase_para_unirse(p_codigo text) TO "service_role";
REVOKE ALL ON FUNCTION public.campos_publicos_actividad(p_tipo text, p_campos jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.campos_publicos_actividad(p_tipo text, p_campos jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.campos_publicos_actividad_pre_acrostic(p_tipo text, p_campos jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.campos_publicos_actividad_pre_acrostic(p_tipo text, p_campos jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.campos_publicos_actividad_pre_crossword(p_tipo text, p_campos jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.campos_publicos_actividad_pre_crossword(p_tipo text, p_campos jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.campos_publicos_actividad_pre_matching(p_tipo text, p_campos jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.campos_publicos_actividad_pre_matching(p_tipo text, p_campos jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.campos_publicos_actividad_pre_syllables(p_tipo text, p_campos jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.campos_publicos_actividad_pre_syllables(p_tipo text, p_campos jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.consumir_limite_progreso(p_usuario_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.consumir_limite_progreso(p_usuario_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION public.crear_clase(p_nombre text, p_grado_id integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.crear_clase(p_nombre text, p_grado_id integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.crear_clase(p_nombre text, p_grado_id integer) TO "service_role";
REVOKE ALL ON FUNCTION public.es_admin() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.es_admin() TO "authenticated";
GRANT EXECUTE ON FUNCTION public.es_admin() TO "service_role";
REVOKE ALL ON FUNCTION public.es_superadministrador() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.es_superadministrador() TO "authenticated";
GRANT EXECUTE ON FUNCTION public.es_superadministrador() TO "service_role";
REVOKE ALL ON FUNCTION public.evaluar_detalle_separar_silabas(p_actividad_id text, p_respuesta jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.evaluar_detalle_separar_silabas(p_actividad_id text, p_respuesta jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.evaluar_detalle_separar_silabas(p_actividad_id text, p_respuesta jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.evaluar_intento_actividad(p_actividad_id text, p_respuesta jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.evaluar_intento_actividad(p_actividad_id text, p_respuesta jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.evaluar_intento_actividad(p_actividad_id text, p_respuesta jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.evaluar_respuesta_actividad(p_tipo text, p_campos jsonb, p_respuesta jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.evaluar_respuesta_actividad(p_tipo text, p_campos jsonb, p_respuesta jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.evaluar_respuesta_actividad_pre_acrostic(p_tipo text, p_campos jsonb, p_respuesta jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.evaluar_respuesta_actividad_pre_acrostic(p_tipo text, p_campos jsonb, p_respuesta jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.evaluar_respuesta_actividad_pre_crossword(p_tipo text, p_campos jsonb, p_respuesta jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.evaluar_respuesta_actividad_pre_crossword(p_tipo text, p_campos jsonb, p_respuesta jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.evaluar_respuesta_actividad_pre_syllables(p_tipo text, p_campos jsonb, p_respuesta jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.evaluar_respuesta_actividad_pre_syllables(p_tipo text, p_campos jsonb, p_respuesta jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.generar_token_10() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.generar_token_10() TO "service_role";
REVOKE ALL ON FUNCTION public.generar_token_128(p_prefijo text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.generar_token_128(p_prefijo text) TO "service_role";
REVOKE ALL ON FUNCTION public.get_actividad_publica(p_actividad_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_actividad_publica(p_actividad_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.get_actividad_publica(p_actividad_id text) TO "service_role";
REVOKE ALL ON FUNCTION public.get_libro_completo(p_libro_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_libro_completo(p_libro_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.get_libro_completo(p_libro_id text) TO "service_role";
REVOKE ALL ON FUNCTION public.get_mis_libros_estado() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_mis_libros_estado() TO "authenticated";
GRANT EXECUTE ON FUNCTION public.get_mis_libros_estado() TO "service_role";
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO "service_role";
REVOKE ALL ON FUNCTION public.is_admin(uid uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_admin(uid uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.is_admin(uid uuid) TO "service_role";
REVOKE ALL ON FUNCTION public.is_docente_of(p_usuario_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_docente_of(p_usuario_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.is_docente_of(p_usuario_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION public.is_docente_of_clase(p_clase_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_docente_of_clase(p_clase_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.is_docente_of_clase(p_clase_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION public.is_inscrito_en_clase(p_clase_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_inscrito_en_clase(p_clase_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.is_inscrito_en_clase(p_clase_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION public.marcar_archivos_accion_rechazada() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.marcar_archivos_accion_rechazada() TO "service_role";
REVOKE ALL ON FUNCTION public.normalizar_crucigrama_texto(p_valor text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.normalizar_crucigrama_texto(p_valor text) TO "service_role";
REVOKE ALL ON FUNCTION public.normalizar_orden_unidad_al_insertar() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.normalizar_orden_unidad_al_insertar() TO "authenticated";
GRANT EXECUTE ON FUNCTION public.normalizar_orden_unidad_al_insertar() TO "service_role";
REVOKE ALL ON FUNCTION public.normalizar_respuesta_texto(p_valor text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.normalizar_respuesta_texto(p_valor text) TO "service_role";
REVOKE ALL ON FUNCTION public.normalizar_separacion_silabas(p_valor text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.normalizar_separacion_silabas(p_valor text) TO "service_role";
REVOKE ALL ON FUNCTION public.prevalidar_token_anonimo(p_token text, p_red_hash text, p_dispositivo_hash text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.prevalidar_token_anonimo(p_token text, p_red_hash text, p_dispositivo_hash text) TO "service_role";
REVOKE ALL ON FUNCTION public.proteger_cambio_rol_aprobado() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.proteger_cambio_rol_aprobado() TO "service_role";
REVOKE ALL ON FUNCTION public.puede_acceder_libro(p_libro_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.puede_acceder_libro(p_libro_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.puede_acceder_libro(p_libro_id text) TO "service_role";
REVOKE ALL ON FUNCTION public.puede_acceder_objeto_libro(p_object_name text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.puede_acceder_objeto_libro(p_object_name text) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.puede_acceder_objeto_libro(p_object_name text) TO "service_role";
REVOKE ALL ON FUNCTION public.puede_leer_perfil_de_alumno(p_estudiante_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.puede_leer_perfil_de_alumno(p_estudiante_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.puede_leer_perfil_de_alumno(p_estudiante_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION public.registrar_archivo_libro_staging(p_path text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.registrar_archivo_libro_staging(p_path text) TO "service_role";
REVOKE ALL ON FUNCTION public.registrar_progreso_actividad(p_actividad_id text, p_respuesta jsonb, p_es_correcta boolean, p_guardar_respuesta boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.registrar_progreso_actividad(p_actividad_id text, p_respuesta jsonb, p_es_correcta boolean, p_guardar_respuesta boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.registrar_progreso_actividad(p_actividad_id text, p_respuesta jsonb, p_es_correcta boolean, p_guardar_respuesta boolean) TO "service_role";
REVOKE ALL ON FUNCTION public.registrar_progreso_actividad_pre_phase6_final(p_actividad_id text, p_respuesta jsonb, p_es_correcta boolean, p_guardar_respuesta boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.registrar_progreso_actividad_pre_phase6_final(p_actividad_id text, p_respuesta jsonb, p_es_correcta boolean, p_guardar_respuesta boolean) TO "service_role";
REVOKE ALL ON FUNCTION public.rls_auto_enable() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.rls_auto_enable() TO "service_role";
REVOKE ALL ON FUNCTION public.sesion_es_aal2() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.sesion_es_aal2() TO "anon";
GRANT EXECUTE ON FUNCTION public.sesion_es_aal2() TO "authenticated";
GRANT EXECUTE ON FUNCTION public.sesion_es_aal2() TO "service_role";
REVOKE ALL ON FUNCTION public.superadmin_resolver_accion(p_accion_id uuid, p_aprobar boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.superadmin_resolver_accion(p_accion_id uuid, p_aprobar boolean) TO "service_role";
REVOKE ALL ON FUNCTION public.superadmin_resolver_accion_fase3_interna(p_accion_id uuid, p_aprobar boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.superadmin_resolver_accion_fase3_interna(p_accion_id uuid, p_aprobar boolean) TO "service_role";
REVOKE ALL ON FUNCTION public.superadmin_resolver_accion_v2(p_accion_id uuid, p_aprobar boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.superadmin_resolver_accion_v2(p_accion_id uuid, p_aprobar boolean) TO "service_role";
REVOKE ALL ON FUNCTION public.superadmin_resolver_accion_v3(p_accion_id uuid, p_aprobar boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.superadmin_resolver_accion_v3(p_accion_id uuid, p_aprobar boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.superadmin_resolver_accion_v3(p_accion_id uuid, p_aprobar boolean) TO "service_role";
REVOKE ALL ON FUNCTION public.unirse_clase(p_codigo text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.unirse_clase(p_codigo text) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.unirse_clase(p_codigo text) TO "service_role";
REVOKE ALL ON FUNCTION public.validar_actividad_identificar() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.validar_actividad_identificar() TO "service_role";
REVOKE ALL ON FUNCTION public.validar_payload_respuesta(p_respuesta jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.validar_payload_respuesta(p_respuesta jsonb) TO "service_role";
REVOKE ALL ON FUNCTION public.validar_publicacion_archivos_libro() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.validar_publicacion_archivos_libro() TO "service_role";
REVOKE ALL ON FUNCTION public.verificar_token(p_token text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.verificar_token(p_token text) TO "authenticated";
GRANT EXECUTE ON FUNCTION public.verificar_token(p_token text) TO "service_role";
REVOKE ALL ON SEQUENCE public.grados_id_seq FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON SEQUENCE public.grados_id_seq TO "authenticated";
GRANT UPDATE ON SEQUENCE public.grados_id_seq TO "authenticated";
GRANT USAGE ON SEQUENCE public.grados_id_seq TO "authenticated";
GRANT SELECT ON SEQUENCE public.grados_id_seq TO "service_role";
GRANT UPDATE ON SEQUENCE public.grados_id_seq TO "service_role";
GRANT USAGE ON SEQUENCE public.grados_id_seq TO "service_role";
REVOKE ALL ON SEQUENCE public.intentos_token_anonimos_id_seq FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON SEQUENCE public.intentos_token_anonimos_id_seq TO "authenticated";
GRANT UPDATE ON SEQUENCE public.intentos_token_anonimos_id_seq TO "authenticated";
GRANT USAGE ON SEQUENCE public.intentos_token_anonimos_id_seq TO "authenticated";
GRANT SELECT ON SEQUENCE public.intentos_token_anonimos_id_seq TO "service_role";
GRANT UPDATE ON SEQUENCE public.intentos_token_anonimos_id_seq TO "service_role";
GRANT USAGE ON SEQUENCE public.intentos_token_anonimos_id_seq TO "service_role";
REVOKE ALL ON TABLE public.acciones_admin_pendientes FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON TABLE public.acciones_admin_pendientes TO "authenticated";
GRANT DELETE ON TABLE public.acciones_admin_pendientes TO "service_role";
GRANT INSERT ON TABLE public.acciones_admin_pendientes TO "service_role";
GRANT MAINTAIN ON TABLE public.acciones_admin_pendientes TO "service_role";
GRANT REFERENCES ON TABLE public.acciones_admin_pendientes TO "service_role";
GRANT SELECT ON TABLE public.acciones_admin_pendientes TO "service_role";
GRANT TRIGGER ON TABLE public.acciones_admin_pendientes TO "service_role";
GRANT TRUNCATE ON TABLE public.acciones_admin_pendientes TO "service_role";
GRANT UPDATE ON TABLE public.acciones_admin_pendientes TO "service_role";
REVOKE ALL ON TABLE public.actividad_progreso FROM PUBLIC, anon, authenticated, service_role;
GRANT MAINTAIN ON TABLE public.actividad_progreso TO "authenticated";
GRANT REFERENCES ON TABLE public.actividad_progreso TO "authenticated";
GRANT SELECT ON TABLE public.actividad_progreso TO "authenticated";
GRANT TRIGGER ON TABLE public.actividad_progreso TO "authenticated";
GRANT TRUNCATE ON TABLE public.actividad_progreso TO "authenticated";
GRANT DELETE ON TABLE public.actividad_progreso TO "service_role";
GRANT INSERT ON TABLE public.actividad_progreso TO "service_role";
GRANT MAINTAIN ON TABLE public.actividad_progreso TO "service_role";
GRANT REFERENCES ON TABLE public.actividad_progreso TO "service_role";
GRANT SELECT ON TABLE public.actividad_progreso TO "service_role";
GRANT TRIGGER ON TABLE public.actividad_progreso TO "service_role";
GRANT TRUNCATE ON TABLE public.actividad_progreso TO "service_role";
GRANT UPDATE ON TABLE public.actividad_progreso TO "service_role";
REVOKE ALL ON TABLE public.actividades FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.actividades TO "authenticated";
GRANT INSERT ON TABLE public.actividades TO "authenticated";
GRANT MAINTAIN ON TABLE public.actividades TO "authenticated";
GRANT REFERENCES ON TABLE public.actividades TO "authenticated";
GRANT SELECT ON TABLE public.actividades TO "authenticated";
GRANT TRIGGER ON TABLE public.actividades TO "authenticated";
GRANT TRUNCATE ON TABLE public.actividades TO "authenticated";
GRANT UPDATE ON TABLE public.actividades TO "authenticated";
GRANT DELETE ON TABLE public.actividades TO "service_role";
GRANT INSERT ON TABLE public.actividades TO "service_role";
GRANT MAINTAIN ON TABLE public.actividades TO "service_role";
GRANT REFERENCES ON TABLE public.actividades TO "service_role";
GRANT SELECT ON TABLE public.actividades TO "service_role";
GRANT TRIGGER ON TABLE public.actividades TO "service_role";
GRANT TRUNCATE ON TABLE public.actividades TO "service_role";
GRANT UPDATE ON TABLE public.actividades TO "service_role";
REVOKE ALL ON TABLE public.admin_logs FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON TABLE public.admin_logs TO "authenticated";
GRANT DELETE ON TABLE public.admin_logs TO "service_role";
GRANT INSERT ON TABLE public.admin_logs TO "service_role";
GRANT MAINTAIN ON TABLE public.admin_logs TO "service_role";
GRANT REFERENCES ON TABLE public.admin_logs TO "service_role";
GRANT SELECT ON TABLE public.admin_logs TO "service_role";
GRANT TRIGGER ON TABLE public.admin_logs TO "service_role";
GRANT TRUNCATE ON TABLE public.admin_logs TO "service_role";
GRANT UPDATE ON TABLE public.admin_logs TO "service_role";
REVOKE ALL ON TABLE public.archivos_libro FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON TABLE public.archivos_libro TO "authenticated";
GRANT DELETE ON TABLE public.archivos_libro TO "service_role";
GRANT INSERT ON TABLE public.archivos_libro TO "service_role";
GRANT MAINTAIN ON TABLE public.archivos_libro TO "service_role";
GRANT REFERENCES ON TABLE public.archivos_libro TO "service_role";
GRANT SELECT ON TABLE public.archivos_libro TO "service_role";
GRANT TRIGGER ON TABLE public.archivos_libro TO "service_role";
GRANT TRUNCATE ON TABLE public.archivos_libro TO "service_role";
GRANT UPDATE ON TABLE public.archivos_libro TO "service_role";
REVOKE ALL ON TABLE public.clase_libros FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.clase_libros TO "authenticated";
GRANT INSERT ON TABLE public.clase_libros TO "authenticated";
GRANT MAINTAIN ON TABLE public.clase_libros TO "authenticated";
GRANT REFERENCES ON TABLE public.clase_libros TO "authenticated";
GRANT SELECT ON TABLE public.clase_libros TO "authenticated";
GRANT TRIGGER ON TABLE public.clase_libros TO "authenticated";
GRANT TRUNCATE ON TABLE public.clase_libros TO "authenticated";
GRANT UPDATE ON TABLE public.clase_libros TO "authenticated";
GRANT DELETE ON TABLE public.clase_libros TO "service_role";
GRANT INSERT ON TABLE public.clase_libros TO "service_role";
GRANT MAINTAIN ON TABLE public.clase_libros TO "service_role";
GRANT REFERENCES ON TABLE public.clase_libros TO "service_role";
GRANT SELECT ON TABLE public.clase_libros TO "service_role";
GRANT TRIGGER ON TABLE public.clase_libros TO "service_role";
GRANT TRUNCATE ON TABLE public.clase_libros TO "service_role";
GRANT UPDATE ON TABLE public.clase_libros TO "service_role";
REVOKE ALL ON TABLE public.clases FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.clases TO "authenticated";
GRANT INSERT ON TABLE public.clases TO "authenticated";
GRANT MAINTAIN ON TABLE public.clases TO "authenticated";
GRANT REFERENCES ON TABLE public.clases TO "authenticated";
GRANT SELECT ON TABLE public.clases TO "authenticated";
GRANT TRIGGER ON TABLE public.clases TO "authenticated";
GRANT TRUNCATE ON TABLE public.clases TO "authenticated";
GRANT UPDATE ON TABLE public.clases TO "authenticated";
GRANT DELETE ON TABLE public.clases TO "service_role";
GRANT INSERT ON TABLE public.clases TO "service_role";
GRANT MAINTAIN ON TABLE public.clases TO "service_role";
GRANT REFERENCES ON TABLE public.clases TO "service_role";
GRANT SELECT ON TABLE public.clases TO "service_role";
GRANT TRIGGER ON TABLE public.clases TO "service_role";
GRANT TRUNCATE ON TABLE public.clases TO "service_role";
GRANT UPDATE ON TABLE public.clases TO "service_role";
REVOKE ALL ON TABLE public.escuela_libros FROM PUBLIC, anon, authenticated, service_role;
GRANT MAINTAIN ON TABLE public.escuela_libros TO "authenticated";
GRANT REFERENCES ON TABLE public.escuela_libros TO "authenticated";
GRANT SELECT ON TABLE public.escuela_libros TO "authenticated";
GRANT TRIGGER ON TABLE public.escuela_libros TO "authenticated";
GRANT TRUNCATE ON TABLE public.escuela_libros TO "authenticated";
GRANT UPDATE ON TABLE public.escuela_libros TO "authenticated";
GRANT DELETE ON TABLE public.escuela_libros TO "service_role";
GRANT INSERT ON TABLE public.escuela_libros TO "service_role";
GRANT MAINTAIN ON TABLE public.escuela_libros TO "service_role";
GRANT REFERENCES ON TABLE public.escuela_libros TO "service_role";
GRANT SELECT ON TABLE public.escuela_libros TO "service_role";
GRANT TRIGGER ON TABLE public.escuela_libros TO "service_role";
GRANT TRUNCATE ON TABLE public.escuela_libros TO "service_role";
GRANT UPDATE ON TABLE public.escuela_libros TO "service_role";
REVOKE ALL ON TABLE public.escuelas FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.escuelas TO "authenticated";
GRANT MAINTAIN ON TABLE public.escuelas TO "authenticated";
GRANT REFERENCES ON TABLE public.escuelas TO "authenticated";
GRANT SELECT ON TABLE public.escuelas TO "authenticated";
GRANT TRIGGER ON TABLE public.escuelas TO "authenticated";
GRANT TRUNCATE ON TABLE public.escuelas TO "authenticated";
GRANT DELETE ON TABLE public.escuelas TO "service_role";
GRANT INSERT ON TABLE public.escuelas TO "service_role";
GRANT MAINTAIN ON TABLE public.escuelas TO "service_role";
GRANT REFERENCES ON TABLE public.escuelas TO "service_role";
GRANT SELECT ON TABLE public.escuelas TO "service_role";
GRANT TRIGGER ON TABLE public.escuelas TO "service_role";
GRANT TRUNCATE ON TABLE public.escuelas TO "service_role";
GRANT UPDATE ON TABLE public.escuelas TO "service_role";
REVOKE ALL ON TABLE public.grados FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.grados TO "authenticated";
GRANT INSERT ON TABLE public.grados TO "authenticated";
GRANT MAINTAIN ON TABLE public.grados TO "authenticated";
GRANT REFERENCES ON TABLE public.grados TO "authenticated";
GRANT SELECT ON TABLE public.grados TO "authenticated";
GRANT TRIGGER ON TABLE public.grados TO "authenticated";
GRANT TRUNCATE ON TABLE public.grados TO "authenticated";
GRANT UPDATE ON TABLE public.grados TO "authenticated";
GRANT DELETE ON TABLE public.grados TO "service_role";
GRANT INSERT ON TABLE public.grados TO "service_role";
GRANT MAINTAIN ON TABLE public.grados TO "service_role";
GRANT REFERENCES ON TABLE public.grados TO "service_role";
GRANT SELECT ON TABLE public.grados TO "service_role";
GRANT TRIGGER ON TABLE public.grados TO "service_role";
GRANT TRUNCATE ON TABLE public.grados TO "service_role";
GRANT UPDATE ON TABLE public.grados TO "service_role";
REVOKE ALL ON TABLE public.inscripciones FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.inscripciones TO "authenticated";
GRANT MAINTAIN ON TABLE public.inscripciones TO "authenticated";
GRANT REFERENCES ON TABLE public.inscripciones TO "authenticated";
GRANT SELECT ON TABLE public.inscripciones TO "authenticated";
GRANT TRIGGER ON TABLE public.inscripciones TO "authenticated";
GRANT TRUNCATE ON TABLE public.inscripciones TO "authenticated";
GRANT UPDATE ON TABLE public.inscripciones TO "authenticated";
GRANT DELETE ON TABLE public.inscripciones TO "service_role";
GRANT INSERT ON TABLE public.inscripciones TO "service_role";
GRANT MAINTAIN ON TABLE public.inscripciones TO "service_role";
GRANT REFERENCES ON TABLE public.inscripciones TO "service_role";
GRANT SELECT ON TABLE public.inscripciones TO "service_role";
GRANT TRIGGER ON TABLE public.inscripciones TO "service_role";
GRANT TRUNCATE ON TABLE public.inscripciones TO "service_role";
GRANT UPDATE ON TABLE public.inscripciones TO "service_role";
REVOKE ALL ON TABLE public.intentos_actividad FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.intentos_actividad TO "service_role";
GRANT INSERT ON TABLE public.intentos_actividad TO "service_role";
GRANT MAINTAIN ON TABLE public.intentos_actividad TO "service_role";
GRANT REFERENCES ON TABLE public.intentos_actividad TO "service_role";
GRANT SELECT ON TABLE public.intentos_actividad TO "service_role";
GRANT TRIGGER ON TABLE public.intentos_actividad TO "service_role";
GRANT TRUNCATE ON TABLE public.intentos_actividad TO "service_role";
GRANT UPDATE ON TABLE public.intentos_actividad TO "service_role";
REVOKE ALL ON TABLE public.intentos_clase FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.intentos_clase TO "service_role";
GRANT INSERT ON TABLE public.intentos_clase TO "service_role";
GRANT MAINTAIN ON TABLE public.intentos_clase TO "service_role";
GRANT REFERENCES ON TABLE public.intentos_clase TO "service_role";
GRANT SELECT ON TABLE public.intentos_clase TO "service_role";
GRANT TRIGGER ON TABLE public.intentos_clase TO "service_role";
GRANT TRUNCATE ON TABLE public.intentos_clase TO "service_role";
GRANT UPDATE ON TABLE public.intentos_clase TO "service_role";
REVOKE ALL ON TABLE public.intentos_token FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.intentos_token TO "service_role";
GRANT INSERT ON TABLE public.intentos_token TO "service_role";
GRANT MAINTAIN ON TABLE public.intentos_token TO "service_role";
GRANT REFERENCES ON TABLE public.intentos_token TO "service_role";
GRANT SELECT ON TABLE public.intentos_token TO "service_role";
GRANT TRIGGER ON TABLE public.intentos_token TO "service_role";
GRANT TRUNCATE ON TABLE public.intentos_token TO "service_role";
GRANT UPDATE ON TABLE public.intentos_token TO "service_role";
REVOKE ALL ON TABLE public.intentos_token_anonimos FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.intentos_token_anonimos TO "service_role";
GRANT INSERT ON TABLE public.intentos_token_anonimos TO "service_role";
GRANT MAINTAIN ON TABLE public.intentos_token_anonimos TO "service_role";
GRANT REFERENCES ON TABLE public.intentos_token_anonimos TO "service_role";
GRANT SELECT ON TABLE public.intentos_token_anonimos TO "service_role";
GRANT TRIGGER ON TABLE public.intentos_token_anonimos TO "service_role";
GRANT TRUNCATE ON TABLE public.intentos_token_anonimos TO "service_role";
GRANT UPDATE ON TABLE public.intentos_token_anonimos TO "service_role";
REVOKE ALL ON TABLE public.libro_activaciones FROM PUBLIC, anon, authenticated, service_role;
GRANT MAINTAIN ON TABLE public.libro_activaciones TO "authenticated";
GRANT REFERENCES ON TABLE public.libro_activaciones TO "authenticated";
GRANT SELECT ON TABLE public.libro_activaciones TO "authenticated";
GRANT TRIGGER ON TABLE public.libro_activaciones TO "authenticated";
GRANT TRUNCATE ON TABLE public.libro_activaciones TO "authenticated";
GRANT DELETE ON TABLE public.libro_activaciones TO "service_role";
GRANT INSERT ON TABLE public.libro_activaciones TO "service_role";
GRANT MAINTAIN ON TABLE public.libro_activaciones TO "service_role";
GRANT REFERENCES ON TABLE public.libro_activaciones TO "service_role";
GRANT SELECT ON TABLE public.libro_activaciones TO "service_role";
GRANT TRIGGER ON TABLE public.libro_activaciones TO "service_role";
GRANT TRUNCATE ON TABLE public.libro_activaciones TO "service_role";
GRANT UPDATE ON TABLE public.libro_activaciones TO "service_role";
REVOKE ALL ON TABLE public.libros FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.libros TO "authenticated";
GRANT MAINTAIN ON TABLE public.libros TO "authenticated";
GRANT REFERENCES ON TABLE public.libros TO "authenticated";
GRANT SELECT ON TABLE public.libros TO "authenticated";
GRANT TRIGGER ON TABLE public.libros TO "authenticated";
GRANT TRUNCATE ON TABLE public.libros TO "authenticated";
GRANT DELETE ON TABLE public.libros TO "service_role";
GRANT INSERT ON TABLE public.libros TO "service_role";
GRANT MAINTAIN ON TABLE public.libros TO "service_role";
GRANT REFERENCES ON TABLE public.libros TO "service_role";
GRANT SELECT ON TABLE public.libros TO "service_role";
GRANT TRIGGER ON TABLE public.libros TO "service_role";
GRANT TRUNCATE ON TABLE public.libros TO "service_role";
GRANT UPDATE ON TABLE public.libros TO "service_role";
REVOKE ALL ON TABLE public.limites_progreso FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.limites_progreso TO "service_role";
GRANT INSERT ON TABLE public.limites_progreso TO "service_role";
GRANT MAINTAIN ON TABLE public.limites_progreso TO "service_role";
GRANT REFERENCES ON TABLE public.limites_progreso TO "service_role";
GRANT SELECT ON TABLE public.limites_progreso TO "service_role";
GRANT TRIGGER ON TABLE public.limites_progreso TO "service_role";
GRANT TRUNCATE ON TABLE public.limites_progreso TO "service_role";
GRANT UPDATE ON TABLE public.limites_progreso TO "service_role";
REVOKE ALL ON TABLE public.profiles FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.profiles TO "authenticated";
GRANT MAINTAIN ON TABLE public.profiles TO "authenticated";
GRANT REFERENCES ON TABLE public.profiles TO "authenticated";
GRANT SELECT ON TABLE public.profiles TO "authenticated";
GRANT TRIGGER ON TABLE public.profiles TO "authenticated";
GRANT TRUNCATE ON TABLE public.profiles TO "authenticated";
GRANT DELETE ON TABLE public.profiles TO "service_role";
GRANT INSERT ON TABLE public.profiles TO "service_role";
GRANT MAINTAIN ON TABLE public.profiles TO "service_role";
GRANT REFERENCES ON TABLE public.profiles TO "service_role";
GRANT SELECT ON TABLE public.profiles TO "service_role";
GRANT TRIGGER ON TABLE public.profiles TO "service_role";
GRANT TRUNCATE ON TABLE public.profiles TO "service_role";
GRANT UPDATE ON TABLE public.profiles TO "service_role";
REVOKE ALL ON TABLE public.progreso FROM PUBLIC, anon, authenticated, service_role;
GRANT MAINTAIN ON TABLE public.progreso TO "authenticated";
GRANT REFERENCES ON TABLE public.progreso TO "authenticated";
GRANT SELECT ON TABLE public.progreso TO "authenticated";
GRANT TRIGGER ON TABLE public.progreso TO "authenticated";
GRANT TRUNCATE ON TABLE public.progreso TO "authenticated";
GRANT DELETE ON TABLE public.progreso TO "service_role";
GRANT INSERT ON TABLE public.progreso TO "service_role";
GRANT MAINTAIN ON TABLE public.progreso TO "service_role";
GRANT REFERENCES ON TABLE public.progreso TO "service_role";
GRANT SELECT ON TABLE public.progreso TO "service_role";
GRANT TRIGGER ON TABLE public.progreso TO "service_role";
GRANT TRUNCATE ON TABLE public.progreso TO "service_role";
GRANT UPDATE ON TABLE public.progreso TO "service_role";
REVOKE ALL ON TABLE public.progreso_clase FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.progreso_clase TO "authenticated";
GRANT INSERT ON TABLE public.progreso_clase TO "authenticated";
GRANT MAINTAIN ON TABLE public.progreso_clase TO "authenticated";
GRANT REFERENCES ON TABLE public.progreso_clase TO "authenticated";
GRANT SELECT ON TABLE public.progreso_clase TO "authenticated";
GRANT TRIGGER ON TABLE public.progreso_clase TO "authenticated";
GRANT TRUNCATE ON TABLE public.progreso_clase TO "authenticated";
GRANT UPDATE ON TABLE public.progreso_clase TO "authenticated";
GRANT DELETE ON TABLE public.progreso_clase TO "service_role";
GRANT INSERT ON TABLE public.progreso_clase TO "service_role";
GRANT MAINTAIN ON TABLE public.progreso_clase TO "service_role";
GRANT REFERENCES ON TABLE public.progreso_clase TO "service_role";
GRANT SELECT ON TABLE public.progreso_clase TO "service_role";
GRANT TRIGGER ON TABLE public.progreso_clase TO "service_role";
GRANT TRUNCATE ON TABLE public.progreso_clase TO "service_role";
GRANT UPDATE ON TABLE public.progreso_clase TO "service_role";
REVOKE ALL ON TABLE public.respuestas FROM PUBLIC, anon, authenticated, service_role;
GRANT MAINTAIN ON TABLE public.respuestas TO "authenticated";
GRANT REFERENCES ON TABLE public.respuestas TO "authenticated";
GRANT SELECT ON TABLE public.respuestas TO "authenticated";
GRANT TRIGGER ON TABLE public.respuestas TO "authenticated";
GRANT TRUNCATE ON TABLE public.respuestas TO "authenticated";
GRANT DELETE ON TABLE public.respuestas TO "service_role";
GRANT INSERT ON TABLE public.respuestas TO "service_role";
GRANT MAINTAIN ON TABLE public.respuestas TO "service_role";
GRANT REFERENCES ON TABLE public.respuestas TO "service_role";
GRANT SELECT ON TABLE public.respuestas TO "service_role";
GRANT TRIGGER ON TABLE public.respuestas TO "service_role";
GRANT TRUNCATE ON TABLE public.respuestas TO "service_role";
GRANT UPDATE ON TABLE public.respuestas TO "service_role";
REVOKE ALL ON TABLE public.superadministradores FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON TABLE public.superadministradores TO "authenticated";
GRANT DELETE ON TABLE public.superadministradores TO "service_role";
GRANT INSERT ON TABLE public.superadministradores TO "service_role";
GRANT MAINTAIN ON TABLE public.superadministradores TO "service_role";
GRANT REFERENCES ON TABLE public.superadministradores TO "service_role";
GRANT SELECT ON TABLE public.superadministradores TO "service_role";
GRANT TRIGGER ON TABLE public.superadministradores TO "service_role";
GRANT TRUNCATE ON TABLE public.superadministradores TO "service_role";
GRANT UPDATE ON TABLE public.superadministradores TO "service_role";
REVOKE ALL ON TABLE public.tokens FROM PUBLIC, anon, authenticated, service_role;
GRANT DELETE ON TABLE public.tokens TO "authenticated";
GRANT MAINTAIN ON TABLE public.tokens TO "authenticated";
GRANT REFERENCES ON TABLE public.tokens TO "authenticated";
GRANT SELECT ON TABLE public.tokens TO "authenticated";
GRANT TRIGGER ON TABLE public.tokens TO "authenticated";
GRANT TRUNCATE ON TABLE public.tokens TO "authenticated";
GRANT DELETE ON TABLE public.tokens TO "service_role";
GRANT INSERT ON TABLE public.tokens TO "service_role";
GRANT MAINTAIN ON TABLE public.tokens TO "service_role";
GRANT REFERENCES ON TABLE public.tokens TO "service_role";
GRANT SELECT ON TABLE public.tokens TO "service_role";
GRANT TRIGGER ON TABLE public.tokens TO "service_role";
GRANT TRUNCATE ON TABLE public.tokens TO "service_role";
GRANT UPDATE ON TABLE public.tokens TO "service_role";
REVOKE ALL ON TABLE public.unidades FROM PUBLIC, anon, authenticated, service_role;
GRANT MAINTAIN ON TABLE public.unidades TO "authenticated";
GRANT REFERENCES ON TABLE public.unidades TO "authenticated";
GRANT SELECT ON TABLE public.unidades TO "authenticated";
GRANT TRIGGER ON TABLE public.unidades TO "authenticated";
GRANT TRUNCATE ON TABLE public.unidades TO "authenticated";
GRANT DELETE ON TABLE public.unidades TO "service_role";
GRANT INSERT ON TABLE public.unidades TO "service_role";
GRANT MAINTAIN ON TABLE public.unidades TO "service_role";
GRANT REFERENCES ON TABLE public.unidades TO "service_role";
GRANT SELECT ON TABLE public.unidades TO "service_role";
GRANT TRIGGER ON TABLE public.unidades TO "service_role";
GRANT TRUNCATE ON TABLE public.unidades TO "service_role";
GRANT UPDATE ON TABLE public.unidades TO "service_role";
COMMIT;
